"use client";
import { useState } from "react";
import { addEvent, addPlan, deleteEvent, deletePlan, saveDay, togglePlan } from "./actions";

type DayData={id:string;date:Date;title:string|null;thoughts:string|null;gratitude:string|null;highlights:string|null;challenges:string|null;wins:string|null;mood:"VERY_LOW"|"LOW"|"OKAY"|"GOOD"|"GREAT"|null;energy:number|null;stress:number|null;productivity:number|null;social:number|null;sleep:number|null;events:{id:string;time:string|null;title:string;description:string|null;category:string|null}[];plans:{id:string;title:string;completed:boolean}[]};
const moods=[["VERY_LOW","Very low","😞"],["LOW","Low","😕"],["OKAY","Okay","😐"],["GOOD","Good","🙂"],["GREAT","Great","😄"]] as const;
const metrics=[["energy","Energy"],["stress","Stress"],["productivity","Productivity"],["social","Social"],["sleep","Sleep"]] as const;

export function TodayEditor({day}:{day:DayData;dateKey:string}){
 const [saving,setSaving]=useState(false); const progress=day.plans.length?Math.round(day.plans.filter(p=>p.completed).length/day.plans.length*100):0;
 return <div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]">
  <div className="space-y-5">
   <form action={async fd=>{setSaving(true);try{await saveDay(fd)}finally{setSaving(false)}}} className="card p-5 sm:p-7">
    <div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-semibold">The day</h2><p className="mt-1 text-sm text-[var(--muted)]">Capture enough to remember it. Nothing more is required.</p></div><button disabled={saving} className="button-primary">{saving?"Saving…":"Save day"}</button></div>
    <input type="hidden" name="dayId" value={day.id}/>
    <label className="mt-6 block text-sm"><span className="label">Title</span><input name="title" defaultValue={day.title??""} className="field" placeholder="Give the day a name"/></label>
    <div className="mt-6"><span className="label">Mood</span><div className="grid grid-cols-5 gap-2">{moods.map(([v,l,e])=><label key={v} className="cursor-pointer"><input type="radio" name="mood" value={v} defaultChecked={day.mood===v} className="peer sr-only"/><span className="flex min-h-20 flex-col items-center justify-center rounded-2xl border border-[var(--border)] p-2 text-center transition peer-checked:border-[var(--accent)] peer-checked:bg-[var(--accent)]/10"><span className="text-2xl">{e}</span><span className="mt-1 text-[11px] text-[var(--muted)]">{l}</span></span></label>)}</div></div>
    <div className="mt-6 grid gap-3 sm:grid-cols-5">{metrics.map(([n,l])=><label key={n} className="text-xs text-[var(--muted)]"><span className="mb-2 block">{l} · 1–5</span><select name={n} defaultValue={String((day as Record<string,unknown>)[n]??"")} className="field"><option value="">—</option>{[1,2,3,4,5].map(v=><option key={v} value={v}>{v}</option>)}</select></label>)}</div>
    <div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="text-sm"><span className="label">Thoughts</span><textarea name="thoughts" defaultValue={day.thoughts??""} rows={7} className="field resize-y" placeholder="What stayed with you today?"/></label><div className="grid gap-4"><label className="text-sm"><span className="label">Highlights</span><textarea name="highlights" defaultValue={day.highlights??""} rows={3} className="field resize-y" placeholder="What do you want to remember?"/></label><label className="text-sm"><span className="label">Small wins</span><textarea name="wins" defaultValue={day.wins??""} rows={3} className="field resize-y" placeholder="What are you glad you did?"/></label></div></div>
    <div className="mt-4 grid gap-5 sm:grid-cols-2"><label className="text-sm"><span className="label">Gratitude</span><textarea name="gratitude" defaultValue={day.gratitude??""} rows={3} className="field resize-y" placeholder="Something you appreciated"/></label><label className="text-sm"><span className="label">Challenges</span><textarea name="challenges" defaultValue={day.challenges??""} rows={3} className="field resize-y" placeholder="What was difficult?"/></label></div>
   </form>
   <section className="card p-5 sm:p-7"><div className="flex items-end justify-between"><div><p className="eyebrow">Timeline</p><h2 className="mt-2 text-xl font-semibold">Moments worth keeping</h2></div><span className="pill">{day.events.length} moments</span></div>
    <div className="mt-5 space-y-2">{day.events.length?day.events.map(e=><div key={e.id} className="flex gap-3 rounded-2xl border border-[var(--border)] p-4"><span className="w-12 shrink-0 text-xs text-[var(--muted)]">{e.time||"—"}</span><div className="min-w-0 flex-1"><p className="font-medium">{e.title}</p>{e.description&&<p className="mt-1 text-sm text-[var(--muted)]">{e.description}</p>}</div><form action={deleteEvent}><input type="hidden" name="eventId" value={e.id}/><button className="text-xs text-[var(--muted)]">Delete</button></form></div>):<p className="rounded-2xl border border-dashed border-[var(--border)] p-5 text-sm text-[var(--muted)]">No moments yet.</p>}</div>
    <form action={addEvent} className="mt-4 grid gap-2 sm:grid-cols-[90px_1fr_120px_auto]"><input type="hidden" name="dayId" value={day.id}/><input name="time" type="time" className="field"/><input name="title" required className="field" placeholder="What happened?"/><input name="category" className="field" placeholder="Category"/><button className="button-primary">Add</button><textarea name="description" className="field sm:col-span-4" rows={2} placeholder="Optional detail"/></form>
   </section>
  </div>
  <aside><section className="card p-5 sm:p-7 sticky top-24"><p className="eyebrow">Plan for today</p><div className="mt-2 flex items-end justify-between"><h2 className="text-xl font-semibold">{progress}% complete</h2><span className="text-xs text-[var(--muted)]">{day.plans.filter(p=>p.completed).length}/{day.plans.length}</span></div><div className="mt-3 h-2 rounded-full bg-[var(--border)]"><div className="h-full rounded-full bg-[var(--accent)]" style={{width:`${progress}%`}}/></div><div className="mt-5 space-y-2">{day.plans.map(p=><div key={p.id} className="flex items-center gap-2 rounded-xl border border-[var(--border)] p-3"><form action={togglePlan}><input type="hidden" name="planId" value={p.id}/><button className={`grid size-7 place-items-center rounded-full border text-xs ${p.completed?"border-[var(--accent)] bg-[var(--accent)] text-white":"border-[var(--border)]"}`}>{p.completed?"✓":""}</button></form><span className={`min-w-0 flex-1 text-sm ${p.completed?"text-[var(--muted)] line-through":""}`}>{p.title}</span><form action={deletePlan}><input type="hidden" name="planId" value={p.id}/><button className="text-xs text-[var(--muted)]">×</button></form></div>)}</div>{day.plans.length===0&&<p className="mt-5 text-sm text-[var(--muted)]">Add a few intentions below.</p>}<form action={addPlan} className="mt-4 flex gap-2"><input type="hidden" name="dayId" value={day.id}/><input name="title" required className="field" placeholder="Add an intention"/><button className="button-primary">Add</button></form></section></aside>
 </div>
}
