"use client";

import { useState } from "react";
import { addEvent, addPlan, deleteEvent, deletePlan, saveDay, togglePlan } from "./actions";

type DayData = {
  id:string; date:Date; title:string|null; thoughts:string|null; gratitude:string|null; highlights:string|null; challenges:string|null; wins:string|null;
  mood:"VERY_LOW"|"LOW"|"OKAY"|"GOOD"|"GREAT"|null; energy:number|null; stress:number|null; productivity:number|null; social:number|null; sleep:number|null;
  events:{id:string;time:string|null;title:string;description:string|null;category:string|null}[];
  plans:{id:string;title:string;completed:boolean}[];
};
const moods=[['VERY_LOW','Very low','😞'],['LOW','Low','😕'],['OKAY','Okay','😐'],['GOOD','Good','🙂'],['GREAT','Great','😄']] as const;
const metrics=[['energy','Energy'],['stress','Stress'],['productivity','Productivity'],['social','Social'],['sleep','Sleep']] as const;
export function TodayEditor({day,dateKey}:{day:DayData;dateKey:string}){
  const [saving,setSaving]=useState(false);
  return <div className="grid gap-6 lg:grid-cols-[1.25fr_.75fr]">
    <div className="space-y-6">
      <form action={async(fd)=>{setSaving(true);try{await saveDay(fd)}finally{setSaving(false)}}} className="card p-5 sm:p-7">
        <input type="hidden" name="dayId" value={day.id}/>
        <div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-semibold">How was your day?</h2><p className="mt-1 text-sm text-[var(--muted)]">You can keep it short. DayShelf is meant to be easy to return to.</p></div><button disabled={saving} className="button-primary shrink-0">{saving?'Saving…':'Save day'}</button></div>
        <label className="mt-6 block text-sm"><span className="mb-2 block font-medium">Title</span><input name="title" defaultValue={day.title??''} className="field" placeholder="Give today a little name"/></label>
        <div className="mt-6"><span className="mb-3 block text-sm font-medium">Mood</span><div className="grid grid-cols-5 gap-2">{moods.map(([value,label,emoji])=><label key={value} className="cursor-pointer"><input type="radio" name="mood" value={value} defaultChecked={day.mood===value} className="peer sr-only"/><span className="flex min-h-20 flex-col items-center justify-center rounded-2xl border border-[var(--border)] p-2 text-center transition peer-checked:border-[var(--accent)] peer-checked:bg-[var(--accent)]/10"><span className="text-2xl">{emoji}</span><span className="mt-1 text-[11px] text-[var(--muted)]">{label}</span></span></label>)}</div></div>
        <div className="mt-6 grid gap-3 sm:grid-cols-5">{metrics.map(([name,label])=><label key={name} className="text-xs text-[var(--muted)]"><span className="mb-2 block">{label} <span className="opacity-60">1–5</span></span><select name={name} defaultValue={String((day as Record<string, unknown>)[name] ?? '')} className="field"><option value="">—</option>{[1,2,3,4,5].map(v=><option key={v} value={v}>{v}</option>)}</select></label>)}</div>
        <div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="text-sm"><span className="mb-2 block font-medium">Thoughts</span><textarea name="thoughts" defaultValue={day.thoughts??''} rows={6} className="field resize-y" placeholder="What is on your mind?"/></label><div className="grid gap-5"><label className="text-sm"><span className="mb-2 block font-medium">Highlights</span><textarea name="highlights" defaultValue={day.highlights??''} rows={3} className="field resize-y" placeholder="What do you want to remember?"/></label><label className="text-sm"><span className="mb-2 block font-medium">Small wins</span><textarea name="wins" defaultValue={day.wins??''} rows={3} className="field resize-y" placeholder="Anything you are glad you did?"/></label></div></div>
        <div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="text-sm"><span className="mb-2 block font-medium">Gratitude</span><textarea name="gratitude" defaultValue={day.gratitude??''} rows={3} className="field resize-y" placeholder="Something you appreciated"/></label><label className="text-sm"><span className="mb-2 block font-medium">Challenges</span><textarea name="challenges" defaultValue={day.challenges??''} rows={3} className="field resize-y" placeholder="What was difficult?"/></label></div>
      </form>

      <section className="card p-5 sm:p-7"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Timeline</h2><p className="mt-1 text-sm text-[var(--muted)]">Capture moments without writing a full story.</p></div><span className="rounded-full bg-[var(--accent)]/10 px-3 py-1 text-xs text-[var(--accent)]">{day.events.length} moments</span></div>
        <div className="mt-6 space-y-3">{day.events.length===0?<p className="rounded-2xl border border-dashed border-[var(--border)] p-5 text-sm text-[var(--muted)]">Nothing added yet. Start with one moment you want to remember.</p>:day.events.map(e=><div key={e.id} className="flex gap-4 rounded-2xl border border-[var(--border)] p-4"><div className="w-14 shrink-0 text-xs text-[var(--muted)]">{e.time||'—'}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{e.title}</p>{e.category&&<span className="rounded-full bg-[var(--accent)]/10 px-2 py-0.5 text-[11px] text-[var(--accent)]">{e.category}</span>}</div>{e.description&&<p className="mt-1 text-sm text-[var(--muted)]">{e.description}</p>}</div><form action={deleteEvent}><input type="hidden" name="eventId" value={e.id}/><button className="text-xs text-[var(--muted)] hover:text-red-400">Delete</button></form></div>)}</div>
        <form action={addEvent} className="mt-5 grid gap-3 sm:grid-cols-[90px_1fr_130px_auto]"><input type="hidden" name="dayId" value={day.id}/><input name="time" type="time" className="field"/><input name="title" required className="field" placeholder="What happened?"/><input name="category" className="field" placeholder="Category"/><button className="button-primary">Add</button><textarea name="description" className="field sm:col-span-4" rows={2} placeholder="Optional details"/></form>
      </section>
    </div>

    <aside className="space-y-6"><section className="card p-5 sm:p-7"><div><h2 className="text-xl font-semibold">Today&apos;s plans</h2><p className="mt-1 text-sm text-[var(--muted)]">Keep the list small enough to finish.</p></div><div className="mt-5 space-y-2">{day.plans.length===0?<p className="rounded-2xl border border-dashed border-[var(--border)] p-4 text-sm text-[var(--muted)]">No plans yet.</p>:day.plans.map(p=><div key={p.id} className="flex items-center gap-3 rounded-2xl border border-[var(--border)] p-3"><form action={togglePlan}><input type="hidden" name="planId" value={p.id}/><button aria-label={p.completed?'Mark incomplete':'Mark complete'} className={`grid size-7 place-items-center rounded-full border text-xs ${p.completed?'border-[var(--accent)] bg-[var(--accent)] text-white':'border-[var(--border)]'}`}>{p.completed?'✓':''}</button></form><span className={`min-w-0 flex-1 text-sm ${p.completed?'text-[var(--muted)] line-through':''}`}>{p.title}</span><form action={deletePlan}><input type="hidden" name="planId" value={p.id}/><button className="text-xs text-[var(--muted)] hover:text-red-400">×</button></form></div>)}</div><form action={addPlan} className="mt-4 flex gap-2"><input type="hidden" name="dayId" value={day.id}/><input name="title" required className="field" placeholder="Add a plan"/><button className="button-primary">Add</button></form>{day.plans.length>0&&<div className="mt-5"><div className="flex justify-between text-xs text-[var(--muted)]"><span>Progress</span><span>{Math.round(day.plans.filter(p=>p.completed).length/day.plans.length*100)}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[var(--border)]"><div className="h-full rounded-full bg-[var(--accent)]" style={{width:`${day.plans.filter(p=>p.completed).length/day.plans.length*100}%`}}/></div></div>}</section>
      <section className="rounded-[1.5rem] border border-dashed border-[var(--border)] p-5"><p className="text-sm font-medium">V1 journal core</p><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Calendar, richer editing, weekly/monthly reflection, goals and memories will build on this Day object. Every journal operation is checked against the signed-in user.</p></section>
    </aside>
  </div>;
}
